### ISSUE TITLE
[UPDATE] DropDown Menu

### ISSUE THREAD

**Issue by blu-rayy** [blu-rayy/Java-LMS#30]
Drop Down Menu color not properly functioning

**Comment by hottodoggu123** [comment]
endless cycle of suffering

**Comment by blu-rayy** [comment]
stop this now

**Comment by blu-rayy** [comment]
On Member_DashboardGUI, the issue is still persistent

![image](https://github.com/user-attachments/assets/c185e220-5d35-4eff-9e2f-f5bdadf7271e)

**Comment by hottodoggu123** [comment]
uhhh,,,,
